fix exercise solution in ex-data-filter
rstudio/learnr pull request #444
Opened 2020-10-17 21:30 UTC by helix84

arr_delay is in minutes

2020-10-17 21:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/learnr?pullRequest=444) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/learnr?pullRequest=444) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/learnr?pullRequest=444) it.</sub>

2020-10-19 16:03 UTC, schloerke requested changes

2020-10-19 16:03 UTC, schloerke commented on inst/tutorials/ex-data-filter/ex-data-filter.Rmd
> +    filter(flights, dep_delay > 60, (dep_delay - arr_delay) > 30)
Can we also change the wording of this question from `but made up over 30 minutes` to `but made up more than 30 minutes`?

Thank you!

2021-01-12 19:01 UTC, gadenbuie approved these changes
I made the change @schloerke requested and also separated the hints in the final exercise (added in this PR) into individual hints for readability

2021-01-14 22:48 UTC, schloerke commented on inst/tutorials/ex-data-filter/ex-data-filter.Rmd
> +1. Were delayed by at least an hour, but made up more than 30 minutes in flight
```suggestion
1. Were delayed more than an hour, but made up more than 30 minutes in flight
```

2021-01-14 22:53 UTC, merged