More internationalization
rstudio/learnr pull request #456
Opened 2020-12-23 18:31 UTC by gadenbuie

This PR builds on #441 (and includes the history in that branch) to extend the internationalization features and to expose the configuration options to the user for customization at a per-tutorial basis.

The usage and new format of the `language` option is outlined in the updated `multilang` vignette. There are quite a few different possibilities for the YAML options, ranging from simply changing the base language of the tutorial

```yaml
language: fr
```

to overriding the display text for a specific language

```yaml
# customize English display text for specific elements
language:
  default: en
  custom:
    button:
      runcode: Run!
    text:
      areyousure: Are you certain?
```

or to override the display text for multiple languages

```yaml
language:
  default: en
  custom:
    - language: en
      button:
        runcode: Run!
    - language: es
      button:
        runcode: Ejecutar
```

or to provide the customizations in a JSON file

```yaml
language:
  default: en
  custom: custom-language.json
```

## Technical Changes

I've made a few changes compared with the approach in #441 that I'll outline briefly.

The first is that complete translations are now in R in `tutorial_i18n_translations()`. I think this will make it easier for R users to contribute more translations.

`tutorial_i18n_lang()` now receives the entire `language` list item from `learnr::tutorial()`, which is processed into a resources list as expected by `i18next` in `tutorial_i18n_process_language_options()` and written into the `.js` file containing the initialization code by `tutorial_i18n_prepare_language_file()`. Finally `tutorial_i18n_lang()` returns the `htmlDependency()` for the `i18next` initialization which contains the user's customizations.

Previously, a small amount of work was done to not re-create the initialization dependency file. Because that file can now depend on another external file (the `custom-language.json` file), I didn't really see any performance benefit to avoiding re-writing the file, so we now just write it on every render.

Users now have the `multilang` vignette and the documentation from `tutorial_i18n_custom_language()` to learn about language customization options. The latter is exported to facilitate creating the JSON file and to perform minimal validation of the custom language options.

Because the translations have been moved into R functions, the function documentation and the vignette both update automatically, so new translations can be added by updating `tutorial_i18n_translations()` without needing to update documentation in multiple locations.

2020-12-23 18:45 UTC, gadenbuie commented
CI failures are from unicode emoji, like `"\U0001f3c3"`, causing a non-ASCII characters in R code warning. @schloerke Any idea how to get around this?

2021-01-06 18:24 UTC, gadenbuie commented
```yaml
language:
  en:
    button:
      runcode: Run!
    text:
      areyousure: Are you certain?
  es:
    button:
      runcode: Ejecutar
  fr: fr-translation.json
```

2021-01-06 18:27 UTC, schloerke requested changes
Implement this change: https://github.com/rstudio/learnr/pull/456#issuecomment-755476766

2021-01-06 18:28 UTC, schloerke commented
Let's also convert to htmldependencies

2021-01-13 14:27 UTC, gadenbuie commented on R/html-dependencies.R
> +      type = "text/json",
```suggestion
      type = "application/json",
```

2021-01-13 15:18 UTC, schloerke commented on R/html-dependencies.R
> +    ))
Nice!

2021-01-13 15:18 UTC, schloerke commented on R/quiz.R
> +  is_default_label <- identical(format(button_label), default_label)
Does the right side need to be formatted?

2021-01-13 15:18 UTC, schloerke commented on R/tutorial-format.R
> +#'        formatting.
I still have trouble knowing where to look.

```suggestion
#' @param language Language or custom text of the UI elements. See 
#'        `vignette("multilang", package = "learnr")` for more information 
#'        about available options and formatting
```

2021-01-13 15:18 UTC, schloerke commented on inst/lib/tutorial/tutorial.js
> +        binding.should_check = ev.delegateTarget.hasAttribute('data-check');
Why this change?

2021-01-13 15:18 UTC, schloerke commented on inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
> +        }
Can we make a small helper method for this? It is repeated many times

2021-01-13 15:18 UTC, schloerke commented on inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
> +        bootbox.setLocale(i18next.language || window.localStorage.i18nextLng || "en")
And a helper method for this, too

2021-01-13 15:21 UTC, schloerke requested changes
Needs a news entry

2021-01-13 15:24 UTC, gadenbuie commented on inst/lib/tutorial/tutorial.js
> +        binding.should_check = ev.delegateTarget.hasAttribute('data-check');
This is the jQuery version of `event.currentTarget`. One of the two is needed because the event listener is attached to the button but this PR introduces a span child of the button element, so `event.target` might point to the span depending on the location of the click. I chose the jQuery version `event.delegateTarget` because it likely has better browser coverage.

2021-01-13 15:26 UTC, gadenbuie commented on R/quiz.R
> +  is_default_label <- identical(format(button_label), default_label)
Or unclassed. The issue is that by now `button_label` has been promoted to `HTML()` so it has an extra `"html"` class so that even if it is the default value it won't be identical to the default value of the argument in `question()`.

2021-01-13 15:27 UTC, gadenbuie commented on R/tutorial-format.R
> +#'        formatting.
Does your suggestion fix the trouble or should we add more here?

2021-01-13 15:50 UTC, schloerke commented on R/tutorial-format.R
> +#'        formatting.
Sorry for being unclear. I have trouble remembering how to view a vignette. 

So we should use the suggestion above (or something similar), which gives me something to run or a link to click to view the information.

2021-01-13 15:51 UTC, schloerke commented on inst/lib/tutorial/tutorial.js
> +        binding.should_check = ev.delegateTarget.hasAttribute('data-check');
🙌

2021-01-13 16:05 UTC, schloerke commented on R/quiz.R
> +  is_default_label <- identical(format(button_label), default_label)
```suggestion
  # At this point, `button_label` has been upgraded to HTML. 
  # Need to format() for a fair comparison
  is_default_label <- identical(format(button_label), default_label)
```

2021-01-13 22:32 UTC, gadenbuie commented on inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
> +        }
Turns out this is equivalent to the more idiomatic `i18next.t(['key', 'fallback text'])`

2021-01-13 22:32 UTC, gadenbuie commented on inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
> +        }
https://www.i18next.com/translation-function/essentials#multiple-fallback-keys

2021-01-13 22:32 UTC, gadenbuie commented on inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
> +        bootbox.setLocale(i18next.language || window.localStorage.i18nextLng || "en")
I added a helper for looking up the language but there's not much else to refactor here.

2021-01-13 22:37 UTC, gadenbuie commented
A final thought: we might consider updating the documentation build process to also pull in vignettes, similar to pkgdown, so that the multilang vignette can be hosted online as well.

2021-01-13 23:05 UTC, schloerke commented on inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
> +          {count: section.exercises.length, lngs: [i18nextLang(), 'en']}
Is this where `text.exercise_plural` is handled?

2021-01-13 23:05 UTC, schloerke commented on inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
> +    }
Much cleaner! Thank you

2021-01-13 23:07 UTC, schloerke approved these changes
LGTM given `exercise_plural` can be utilized

2021-01-14 20:13 UTC, gadenbuie commented
Fixes #108 
Fixes #388 
Closes #441

2021-01-14 20:39 UTC, gadenbuie commented on inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
> +          {count: section.exercises.length, lngs: [i18nextLang(), 'en']}
Yes, `i18next` uses the `count` option to determine whether to use `text.exercise` or `text.exercise_plural`, following built-in language rules. https://www.i18next.com/translation-function/plurals

2021-01-14 20:58 UTC, gadenbuie commented
Other event listeners may now be targeting the wrong element, in particular the "Start Over" link. I need to do one more pass to check, following changes in [`2159e63` (#456)](https://github.com/rstudio/learnr/pull/456/commits/2159e6383ead7ef4e1030519670eb845f9bc205a)

2021-01-14 21:02 UTC, schloerke commented on inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
> +          {count: section.exercises.length, lngs: [i18nextLang(), 'en']}
Cool!

2021-01-15 19:54 UTC, gadenbuie commented
@schloerke Can you give the last change a quick look? I realized a subtle detail in the way i18next handles fallback languages and namespaces. For historical reasons, if a key is missing in a namespace, i18next falls back to the fallback language key _in that namespace_ before it falls back to the same key in the original language's namespace.

As an example:

```
en:
  custom:
    button.runcode: 'Run'
es:
  translation:
    button.runcode: 'Ejecutar'
```

I was setting the default namespaces as `custom` and falling back to `translation`. But when looking for the run code in `"es"` i18next would use

```
es:custom:button.runcode || en:custom:button.runcode || es:translation:button.runcode || ...
```

which is not ideal.

The fix I've added is to keep the same `custom` and `translation` namespaces in learnr and in the object we serialized into the HTML. But then, before initializing i18next, I merge the `custom` object into the `translation` object, and then only use the `translation` namespace. This effectively reorders the above fallback path to

```
es:custom:... || es:translation:... || en:custom:... || en:translation:...
```

2021-01-15 21:31 UTC, schloerke commented on inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
> +    function i18nextLang(fallbackLng = 'en') {
Need to make this es5 like. It will be safe guarded by the `|| 'en'`

```suggestion
    function i18nextLang(fallbackLng) {
```

2021-01-15 21:39 UTC, schloerke approved these changes
LGTM given small JS change

2021-01-15 21:40 UTC, gadenbuie commented on inst/rmarkdown/templates/tutorial/resources/tutorial-format.js
> +    function i18nextLang(fallbackLng = 'en') {
Oh right, good catch, thanks!

2021-01-15 21:52 UTC, merged