Update i18n_translations.yml to add basque
rstudio/learnr pull request #489
Opened 2021-02-04 13:43 UTC by mikelmadina

Euskara gehitu - Add basque

## Pull Request

Before you submit a pull request, please do the following:

* Add an entry to NEWS concisely describing what you changed.

* Add unit tests in the tests/testthat directory.

* Run Build->Check Package in the RStudio IDE, or `devtools::check()`, to make sure your change did not add any messages, warnings, or errors.

Doing these things will make it easier for the learnr development team to evaluate your pull request. Even so, we may still decide to modify your code or even not merge it at all. Factors that may prevent us from merging the pull request include:

* breaking backward compatibility
* adding a feature that we do not consider relevant for learnr
* is hard to understand
* is hard to maintain in the future
* is computationally expensive
* is not intuitive for people to use

We will try to be responsive and provide feedback in case we decide not to merge your pull request.

## Minimal reproducible example

Finally, please include a minimal reprex. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never heard of a reprex before, start by reading <https://github.com/jennybc/reprex#what-is-a-reprex>, and follow the advice further down the page. Do NOT include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.
```r
reprex::reprex({
  library(learnr)
  # insert minimal reprex here
})
```

Due to the nature of learnr being interactive, if a reprex is not possible, please include a minimal learnr tutorial RMarkdown file that can be called with `rmarkdown::run` to produce an error or display the error has been fixed.

Delete these instructions once you have read them.

---

Brief description of the original problem and the approach behind your solution.

```r
# insert reprex here
```

PR task list:
- [ ] Update NEWS
- [ ] Add tests (if possible)
- [ ] Update documentation with `devtools::document()`

2021-02-04 13:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/learnr?pullRequest=489) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/learnr?pullRequest=489) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/learnr?pullRequest=489) it.</sub>

2021-02-04 21:14 UTC, gadenbuie commented
Thank you @mikelmadina! Before we accept the pull request, can you please sign the CLA? https://github.com/rstudio/learnr/pull/489#issuecomment-773311563

2021-02-08 18:43 UTC, gadenbuie requested changes
Thanks again @mikelmadina! I just have one question about the translation...

2021-02-08 18:43 UTC, gadenbuie commented on data-raw/i18n_translations.yml
> +    eu: "Aurrera egin baino lehen atal honetako ariketa(k) egin behar d(it)uzu"
The `youmustcomplete`, `exercise` and `inthisection` components are joined together to create a sentence:

```
{youmustcomplete} {exercise} {inthissection}.
```

The advantage is that the internationalization library will automatically pick the singular or plural for `exercise`. So it might look like this for Basque:

```yaml
exercise: 
  eu: ariketa
exercise_plural:
  eu: ariketak
```

Note that the three pieces do not need to map to the English meaning, we just need to be able to split the sentence into the start, the part that needs to be pluralized depending on the number of exercises, and the end.

Is this possible?

2021-02-08 22:40 UTC, mikelmadina commented on data-raw/i18n_translations.yml
> +    eu: "Aurrera egin baino lehen atal honetako ariketa(k) egin behar d(it)uzu"
Hi Garrick

Basque verbs are a terrible headache for people learning basque, as in their auxiliar forms they combine morphological marks for the subject, the direct object (singular or plural), the indirect object, the time (present, past, conditional...); and even the verb's morphological root itself in their more synthetic forms.

So, in this case, the plural mark appears not only in the object, but in the verb as well: "duzu" (verb with singular object mark) VS "dituzu" (verb with plural object mark).

Given that this is the only sentence to be translated, I think this is the easiest solution, since it does not require to rewrite any code to accomodate the basque verbs oddities.

2021-02-09 17:03 UTC, gadenbuie commented on data-raw/i18n_translations.yml
> +    eu: "Aurrera egin baino lehen atal honetako ariketa(k) egin behar d(it)uzu"
Are these two sentences correct?

```
# single exercise
Aurrera egin baino lehen atal honetako ariketa egin behar duzu

# multiple exercises
Aurrera egin baino lehen atal honetako ariketak egin behar dituzu
```

If so we can definitely accommodate this 😄

2021-02-09 17:19 UTC, mikelmadina commented on data-raw/i18n_translations.yml
> +    eu: "Aurrera egin baino lehen atal honetako ariketa(k) egin behar d(it)uzu"
You nailed it! ;o)

2021-02-09 22:23 UTC, gadenbuie commented on data-raw/i18n_translations.yml
> +    eu: "Aurrera egin baino lehen atal honetako ariketa(k) egin behar d(it)uzu"
Great! Thanks again!

2021-02-09 22:31 UTC, merged