Update learnr for compatibility with shinytest
rstudio/learnr pull request #527
Opened 2021-05-06 16:11 UTC by gadenbuie

- Babelified `tutorial-i18n-init.js`
- Clear focus from editor after `setValue()` when in a shinytest session.

### Reprex

#### Tutorial

`learnr-issue-209.Rmd`

````markdown
---
title: "Tutorial"
output: 
  learnr::tutorial:
    progressive: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

## Topic 1

### Exercise 

*Here's a simple exercise with an empty code chunk provided for entering the answer.*

Write the R code required to add two plus two:

```{r two-plus-two, exercise=TRUE}

```

### Exercise with Code

*Here's an exercise with some prepopulated code as well as `exercise.lines = 5` to provide a bit more initial room to work.*

Now write a function that adds any two numbers and then call it:

```{r add-function, exercise=TRUE, exercise.lines = 5}
add <- function() {
  
}
```

## Topic 2

### Exercise with Hint

*Here's an exercise where the chunk is pre-evaulated via the `exercise.eval` option (so the user can see the default output we'd like them to customize). We also add a "hint" to the correct solution via the chunk immediate below labeled `print-limit-hint`.*

Modify the following code to limit the number of rows printed to 5:

```{r print-limit, exercise=TRUE, exercise.eval=TRUE}
mtcars
```

```{r print-limit-hint}
head(mtcars)
```

### Quiz

*You can include any number of single or multiple choice questions as a quiz. Use the `question` function to define a question and the `quiz` function for grouping multiple questions together.*

Some questions to verify that you understand the purposes of various base and recommended R packages:

```{r quiz}
quiz(
  question("Which package contains functions for installing other R packages?",
    answer("base"),
    answer("tools"),
    answer("utils", correct = TRUE),
    answer("codetools")
  ),
  question("Which of the R packages listed below are used to create plots?",
    answer("lattice", correct = TRUE),
    answer("tools"),
    answer("stats"),
    answer("grid", correct = TRUE)
  )
)
```
````

#### shinytest

`tests/shinytest/test-learnr-issue-209.R`

```r
app <- ShinyDriver$new("../../learnr-issue-209.Rmd", seed = 50943)
app$snapshotInit("test-learnr-issue-209")

app$setInputs(`tutorial-exercise-two-plus-two-code-editor` = list(code = "\n2+2\n"))
app$setInputs(`continuebutton-section-exercise` = 1)
Sys.sleep(1)  # Sleep after Continue button is clicked
app$snapshot()
app$setInputs(`tutorial-exercise-add-function-code-editor` = list(code = "add <- function() {\n  2\n}"))
app$snapshot()
app$setInputs(`continuebutton-section-exercise-with-code` = 1)
# move to Topic 2 (no outputs are updated)
app$setInputs(`tutorial-topic` = "section-topic-2", wait_=FALSE, values_=FALSE)
Sys.sleep(0.5)
Sys.sleep(1)  # Sleep after Topic change
app$snapshot()
app$setInputs(`tutorial-exercise-print-limit-code-editor` = list(code = "head(mtcars, 5)\n\n"))
app$snapshot()
app$setInputs(`continuebutton-section-exercise-with-hint` = 1)
app$setInputs(`quiz-1-answer` = "utils")
app$setInputs(`quiz-1-action_button` = "click")
app$snapshot()
app$setInputs(`quiz-2-answer` = "lattice")
app$setInputs(`quiz-2-answer` = c("lattice", "stats"))
app$setInputs(`quiz-2-action_button` = "click")
app$snapshot()
```

2021-05-06 17:05 UTC, schloerke commented on inst/lib/i18n/tutorial-i18n-init.js
> +    } else if (_typeof(x) === "object") {
This line is using the `_typeof()` shim that is defined at the top.

2021-05-06 17:07 UTC, schloerke approved these changes

2021-05-06 17:40 UTC, schloerke requested changes
I'm getting issues on my end. Blocking for now to investigate.

2021-05-27 20:41 UTC, gadenbuie commented
@schloerke it looks like you got everything working here 🎉 Ready to merge?

2021-05-28 14:22 UTC, merged