Make files accessible to tutorials
rstudio/learnr pull request #539
Opened 2021-06-12 23:50 UTC by rossellhayes

This adds two interfaces for making files available to `learnr` tutorials.

1. Any files in a `data/` directory in the same directory as the tutorial Rmd document will be accessible to the tutorial.
2. Calling the function `use_remote_files()` in the `setup` chunk will cache files into a temporary directory and make them available to the tutorial as if they were in the `data/` directory.

2021-06-12 23:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/learnr?pullRequest=539) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/learnr?pullRequest=539) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/learnr?pullRequest=539) it.</sub>

2021-06-14 15:03 UTC, gadenbuie requested changes
This is a great start! I really like how the interface is coming together and I think it will benefit many tutorial authors.

We'll need to think through and account for all of the various ways the underlying options can be set and that files can be added to an exercise. To help with that, I think the next step would be to add several small test tutorials in a folder at `tests/testthat/exercise-files`. Each one can demonstrate an expected use case. Actually writing the tests is going to be a little tricky, but we can work through that step together. In the mean time it will be helpful to have a few examples to test out interactively.

2021-06-14 17:53 UTC, rossellhayes commented on R/file_helpers.R
> +  data_files <- rlang::flatten_chr(list(...))
I guess I was using "remote" here to mean "not in the normal directory". This function works with both URLs and file paths outside of the data directory. Should we only allow URLs as remote files, or do you think this function could use a name change?

2021-06-14 17:59 UTC, gadenbuie commented on R/file_helpers.R
> +  data_files <- rlang::flatten_chr(list(...))
I'm not sure. I can think of a few ways that local files not in the tutorial working directory can cause problems, e.g. a random file elsewhere on my machine that will be inaccessible to a deployed tutorial. But there are also "local" files that we might want to work, such as files included in other R packages and accessed with `system.file()`.

I think that once we have a few reprexes it'll be more clear what we should do with this function.

2021-06-14 20:55 UTC, rossellhayes commented on R/file_helpers.R
> +  knitr::opts_chunk$set(exercise.files = files)
I've set it up now so that if a user has a `data/` directory and uses `use_remote_files()` and manually sets the chunk option, all those files will be accessible to the user. However, I've set a warning if the chunk options are manually set, as this will lead to suboptimal performance (e.g. remote files won't be cached). The warning shows up in the R Markdown pane when the exercise is rendered with the Run button and the console when the the exercise is rendered with `run()`.

2021-06-14 23:56 UTC, rossellhayes commented on R/file_helpers.R
> +  data_files <- rlang::flatten_chr(list(...))
For now I've set a check to ensure remote files are either URLs or package files. We can reevaluate if we find any other beneficial uses.

2021-06-15 18:46 UTC, gadenbuie commented on tests/testthat/test-file_helpers.R
> +  )
Does passing this test also imply that the second call to `use_remote_files()` replaces the files previously declared by the first `use_remote_files()`?

We might need a `with_knitr_opts_chunk()` or a `with_knitr_opts_knit()` equivalent of `withr::with_options()`.

2021-06-15 18:56 UTC, gadenbuie commented on R/file_helpers.R
> +  )
This is fun! But also not very readable. I played with it a bit and decided I like this version slightly better:

```suggestion
  vapply(
    lapply(path, Vectorize(grepl, "pattern"), pattern = .libPaths(), fixed = TRUE),
    any,
    logical(1)
  )
```

but...

2021-06-15 19:20 UTC, gadenbuie commented on R/file_helpers.R
> +  )
...but I think it might be even better as a slightly recursive function

```r
is_system_file <- function(path) {
  if (length(path) > 1) {
    vapply(path, is_system_file, logical(1))
  }
  any(vapply(.libPaths(), grepl, x = path, fixed = TRUE, logical(1)))
}	
```

2021-06-15 19:22 UTC, rossellhayes commented on R/file_helpers.R
> +  )
Love this!

2021-06-21 14:51 UTC, gadenbuie requested changes

2021-06-21 14:51 UTC, gadenbuie commented on tests/testthat/test-exercise.R
> +test_that("data files", {
Could you please split up this test into individual `test_that()` calls? This would let you give each testing block a more descriptive name, e.g. `"data files in data/ are copied into exercise temp dir"`, etc.

2021-06-21 14:51 UTC, gadenbuie commented on R/use_data_dir.R
> +  # First check environment variable, then options(), then default to "data/"
Let's flip this and check options -> env var -> default to `data/`

2021-06-21 14:51 UTC, gadenbuie commented on R/use_data_dir.R
> +    "LEARNR_DATA_DIR", unset = getOption("learnr.data_dir", default = "data")
Let's also change this env var name to `TUTORIAL_DATA_DIR` and `tutorial.data.dir`, since this will likely be set at the _tutorial_ level.

2021-06-21 14:51 UTC, gadenbuie commented on R/use_data_dir.R
> +  if (!dir.exists(source_dir)) {return(invisible(NULL))}
We should report this failure, probably with a warning

2021-06-21 14:51 UTC, gadenbuie commented on R/use_data_dir.R
> +    rlang::abort('The user-facing data directory was not created successfully.')
Where is this error raised? Will it stop a running tutorial?

2021-06-21 14:51 UTC, gadenbuie commented on R/use_data_dir.R
> +    rlang::abort('The user-facing data directory was not created successfully.')
Turns out this error is presented to the end-user in the tutorial. I think this wording might make it more clear to users that it isn't their fault and give a better hint to authors.

```suggestion
    rlang::abort("An error occurred: we weren't able to create the data directory for this exercise.")
```

2021-06-21 14:51 UTC, gadenbuie commented on R/use_data_dir.R
> +  if (!dir.exists(source_dir)) {return(invisible(NULL))}
I can see why it's currently invisible -- if there isn't a `data/` directory we don't want to add a lot of noise. So we should put some thought into how we can surface warnings when its clear that the user would want to see them without creating  noise for tutorials without data folders.

2021-06-21 14:51 UTC, gadenbuie commented on R/initialize.R
> +
```suggestion

```

2021-06-21 14:51 UTC, gadenbuie commented on R/use_data_dir.R
> +copy_data_dir <- function(exercise_dir) {
What do you think of making `source_dir` an argument of `copy_data_dir()` and adding a `data_dir` argument to `evaluate_exercise()`?

2021-06-21 15:58 UTC, rossellhayes commented on R/use_data_dir.R
> +  # First check environment variable, then options(), then default to "data/"
My thinking here was that the envvar would be set when the tutorial is deployed on a remote server, and in that case the option set by the author wouldn't necessarily be a valid path anymore. But that makes me wonder if using `options()` is the wrong approach for this. How would the remote deployment know which directories it needs? Maybe non-default directories should be handled in the YAML rather than the setup chunk?

2021-06-21 15:59 UTC, rossellhayes commented on R/use_data_dir.R
> +copy_data_dir <- function(exercise_dir) {
I think this makes sense, especially with my earlier comment about potentially using the YAML

2021-06-21 16:08 UTC, rossellhayes commented on R/use_data_dir.R
> +  if (!dir.exists(source_dir)) {return(invisible(NULL))}
I've changed this to return invisibly if "data/" doesn't exist, but to raise an error if a different directory is specified (by envvar or `options()`) and that directory doesn't exist (5b4a0ee).

2021-06-21 17:27 UTC, gadenbuie commented on R/use_data_dir.R
> +  # First check environment variable, then options(), then default to "data/"
I think that options > env var is the right order. The R process can read the env var, so the author who sets the option can also read and use the env var. In other words, letting the env var overwrite the option removes flexibility. I have the same wonder about whether or not we should use `options()`, though.

2021-06-21 17:30 UTC, gadenbuie commented on R/use_data_dir.R
> +}
This is one of those times when it's okay to copy/paste the same thing in a couple places; I'm not sure there's much if any benefit of having this in a function.

2021-06-21 17:38 UTC, gadenbuie commented on R/use_data_dir.R
> +    if (source_dir == "data") return(invisible(NULL))
I think a better signal might be to set the fallback default value of `source_dir` to `""`. Then if `identical(source_dir, "")` check if `data/` exists in the current working directory, and if it doesn't you can exit quietly. Otherwise, exit loudly if we can't find `data/` or proceed as normal. The benefit is that if a user explicitly sets `option(tutorial.data.dir = "data")`, we'll give an error.

2021-06-21 18:59 UTC, rossellhayes commented on R/use_data_dir.R
> +    if (source_dir == "data") return(invisible(NULL))
I like this solution, implemented in 6672a55

2021-06-23 17:22 UTC, gadenbuie commented on R/exercise.R
> +    source_dir <- Sys.getenv(
I think we lost the `tutorial.data_dir` option in this step. We definitely want to look at R option -> env var -> final default

2021-06-23 17:22 UTC, gadenbuie commented on R/exercise.R
> +      unset = if (dir.exists("data")) {"data"} else {""}
```suggestion
      unset = if (dir.exists("data")) "data" else ""
```

2021-06-23 17:25 UTC, gadenbuie commented on R/data_dir.R
> +            "we weren't able to find the data directory for this exercise."),
```suggestion
      "An error occurred with the tutorial: the data directory does not exist.",
```

2021-06-23 17:26 UTC, gadenbuie commented on R/data_dir.R
> +      class = "learnr.missing_source_dir"
```suggestion
      class = "learnr_missing_source_data_dir"
```

2021-06-23 17:26 UTC, gadenbuie commented on R/data_dir.R
> +            "we weren't able to create the data directory for this exercise."),
```suggestion
      "An error occurred with the tutorial: we weren't able to create the data directory for this exercise.",
```

2021-06-23 17:27 UTC, gadenbuie commented on R/data_dir.R
> +      class = "learnr.missing_dest_dir"
```suggestion
      class = "learnr_missing_dest_data_dir"
```

2021-06-23 17:28 UTC, rossellhayes commented on R/exercise.R
> +    source_dir <- Sys.getenv(
I may have misunderstood the goal of the latest change. If we're requiring authors to keep files in the `"data/"` directory, when would this option be set?

2021-06-23 17:36 UTC, gadenbuie commented on R/data_dir.R
> +  file.copy(dir(source_dir, full.names = TRUE), dest_dir, recursive = TRUE)
This works, but wow I can't believe that there isn't a base R way to copy a directory!

2021-06-23 17:38 UTC, gadenbuie commented on R/exercise.R
> +    source_dir <- Sys.getenv(
Somewhere along the way, most likely by an external evaluator. The env var is too high-level in that case.

2021-06-23 17:42 UTC, gadenbuie commented on R/exercise.R
> +    source_dir <- Sys.getenv(
Let's call the option `tutorial.data_dir`

2021-06-24 03:35 UTC, rossellhayes commented on R/exercise.R
> +    source_dir <- Sys.getenv(
That makes sense!

2021-06-24 03:37 UTC, rossellhayes commented on R/data_dir.R
> +  file.copy(dir(source_dir, full.names = TRUE), dest_dir, recursive = TRUE)
I know, it's there in `fs`!

2021-06-24 15:29 UTC, gadenbuie commented on R/exercise.R
> +      )
The braces snuck back in and it's okay not to name the second argument of `getOption()` and `Sys.getenv()`

```suggestion
    source_dir <- getOption(
      "tutorial.data_dir",
      Sys.getenv("TUTORIAL_DATA_DIR", if (dir.exists("data")) "data" else "")
```

2021-06-24 15:42 UTC, gadenbuie commented on tests/testthat/test-exercise.R
> +  withr::with_tempdir({
Thanks to the pattern you started in #544 https://github.com/rstudio/learnr/blob/bcd5dc3ba831bf44d255dc2643201610161dda32/R/exercise.R#L315-L318

I realized we can avoid putting the whole test in `with_tempdir()`

```suggestion
  withr::local_dir(withr::local_tempdir())
```

2021-06-24 15:42 UTC, gadenbuie commented on tests/testthat/test-exercise.R
> +  })
To finish the thought above...

```suggestion
  })
```

2021-06-24 15:45 UTC, gadenbuie commented on tests/testthat/test-exercise.R
> +  withr::with_tempdir({
This is totally worth the effort -- it makes it so much easier to step through the test interactively. withr is really cool 🤯

2021-06-24 15:59 UTC, gadenbuie commented on tests/testthat/test-exercise.R
> +    expect_match(output$html_output, "DEFAULT", fixed = TRUE)
A little trick that we didn't talk about (because I forgot about it until I read through a few tests) is that you can set `check = TRUE` in `mock_exercise()` this uses a debugging exercise checker that returns a value in the `$feedback` item of the exercise result. 

In that flow, you can access any of the objects that were made available to the exercise checker function via `$feedback$checker_args`. So, for example, you can directly access the result of running the user code like this:

```suggestion
    ex <- mock_exercise(
      user_code = 'readLines("data/test.txt")',
      check = TRUE
    )
    res <- evaluate_exercise(ex, envir = new.env())
    expect_equal(res$feedback$checker_args$last_value, "DEFAULT")
```

You can use this trick to run code at various stages of the exercise evaluation that you can then access via the `envir_prep` or `envir_result` environments that are passed to the checker function.

2021-06-24 16:00 UTC, gadenbuie commented on tests/testthat/test-exercise.R
> +    expect_match(readLines("nested/structure/test.txt"), "NESTED", fixed = TRUE)
What do these tests tell us? (I don't think we gain any information from them and we can probably remove them and the others like them.)

2021-06-24 16:04 UTC, gadenbuie commented on tests/testthat/test-exercise.R
> +    expect_match(readLines("data/test.txt"), "DEFAULT", fixed = TRUE)
This test makes sense: we're expecting that `data/test.txt` here refers to our original `data/` directory. (Make a mental bookmark, we'll need to revisit this test when we work out directory precedence.)

2021-06-24 23:02 UTC, rossellhayes commented on tests/testthat/test-exercise.R
> +  withr::with_tempdir({
Elegant!

2021-06-30 19:52 UTC, gadenbuie commented
@rossellhayes I had a few small changes to propose and in the process I merged main into this branch. It turns out that our options-protection work misses options that are `NULL`. In other words `withr::local_options()` doesn't reset options that were `NULL`, so our tests are now failing until we fix that.

```r
options(thing = NULL)
withr::with_options({
  options(thing = "bad")
})
getOption("thing")
#> "bad"
```

To be fair, this same issue will happen with the standard base R pattern too:

```
options(thing = NULL)
local({
  opts <- options()
  on.exit(options(opts), add = TRUE)
  options(thing = "bad")
})
getOption("thing")
#> "bad"
```

We'll have to write a custom `options_restore()` function that _does_ handle `NULL` options.

2021-06-30 21:31 UTC, rossellhayes commented
It looks like this is a known issue: https://github.com/r-lib/withr/issues/57
Will Landau proposes a solution here: https://github.com/r-lib/withr/issues/57#issuecomment-332007780

2021-07-07 15:39 UTC, gadenbuie approved these changes
This looks great and I'm really excited for this feature to land in learnr. I'm approving the PR but we have a little bit more to do in terms of documentation.

- [ ] Add an entry in NEWS under **New Features**
- [ ] Document the new behavior in the learnr docs webpage. I think it makes sense to add a new section in `docs/exercises.Rmd` after [Exercise Setup](https://rstudio.github.io/learnr/exercises.html#Exercise_Setup).
- [ ] Once the above are done and the PR is merged, we'll need to follow up in any related issues to let everyone know about the new feature.

2021-07-08 17:59 UTC, gadenbuie commented on NEWS.md
> +* Tutorials can attach a file directory for use within exercises. Files in a "data/" directory within the same directory as the tutorial R Markdown document will be available from within exercises. (
```suggestion
* When a "data/" directory is found in the same directory as the tutorial R Markdown document, it is now automatically made available within exercises. An alternative directory can be specified using the `tutorial.data_dir` global option. ([#539](https://github.com/rstudio/learnr/pull/539))
```

2021-07-08 20:52 UTC, schloerke approved these changes
LGTM given cosmetic suggestions!

2021-07-08 20:52 UTC, schloerke commented on R/exercise.R
> +  withr::defer(restore_options(options), envir = .local_envir)
While the original code works, seeing a variable `options` quickly has me think that the value is the `options()` function. Let's change it to something other than `options`.

```suggestion
  opts <- options()
  withr::defer(restore_options(opts), envir = .local_envir)
```

2021-07-08 20:52 UTC, schloerke commented on R/exercise.R
> +}
Let's turn this into two methods to not overload the name / functionality

```suggestion
}

local_restore_envvars <- function() {
  envvars <- Sys.getenv()
  withr::defer(restore_envvars(envvars), envir = .local_envir)
}
```

2021-07-08 20:52 UTC, schloerke commented on R/exercise.R
> +  local_restore_options()
```suggestion
  local_restore_options()
  local_restore_envvars()
```

2021-07-08 20:52 UTC, schloerke commented on R/exercise.R
> +  local_restore_options()
```suggestion
  local_restore_options()
  local_restore_envvars()
```

2021-07-08 20:52 UTC, schloerke commented on R/exercise.R
> +}
If you'd like to make a wrapper around these two functions, I'm ok with it.

2021-07-09 14:28 UTC, merged