Protect `options()` from modifications by students
rstudio/learnr pull request #542
Opened 2021-06-17 19:43 UTC by rossellhayes

This modifies `evaluate_exercise()` to capture the state of `options()` when the tutorial is first loaded. This snapshot is restored each time an exercise is run. This allows tutorial authors to still set options in the `setup` chunk. Students can modify options within a chunk, but these options are not carried over to later chunks or subsequent runs of the same chunk.

2021-06-20 22:40 UTC, rossellhayes commented
Are there any other things besides options that need to be protected in this way?

2021-06-21 15:07 UTC, gadenbuie requested changes
Looks great! Just a few comments to simplify the code and improve readability of the tests

2021-06-21 15:07 UTC, gadenbuie commented on R/exercise.R
>    )
I think we can simplify this a bit and avoid the need to check for or store `options`:

```r
  # Render exercise in temporary exercise directory, protecting global options
  rmd_results <- withr::with_options(
    list(),
    withr::with_dir(
      exercise_dir,
      render_exercise(exercise, envir)
    )
  )
```

2021-06-21 15:07 UTC, gadenbuie commented on tests/testthat/test-exercise.R
> +test_that("options() are protected from user modification", {
I think it'd be helpful to break this testing block up into smaller `test_that()` chunks with descriptive names. You can a section divider above this line

```suggestion
# global options are restored after running user code ---------------------

test_that("options() are protected from user modification", {
```

2021-06-21 15:07 UTC, gadenbuie commented on sandbox/options/options-test.Rmd
> +---
We can remove this file from the PR

2021-06-21 16:26 UTC, rossellhayes commented on R/exercise.R
>    )
Much better!

2021-06-21 17:06 UTC, rossellhayes commented
I've found that the same issue with `options()` also applies to environment variables. This is addressed in 15358af.

2021-06-21 17:16 UTC, gadenbuie commented on R/exercise.R
> +  withr::local_envvar(as.list(Sys.getenv()))
This is a good catch! But we should move these into `render_exercise()` so that the options and env vars are reset when exiting `render_exercise()`. Otherwise using `local_*()` will reset the options and env vars too late.

2021-06-23 13:09 UTC, gadenbuie commented on R/exercise.R
> +  withr::local_envvar(as.list(Sys.getenv()))
After a little more thought, I wonder if we might actually need this in both places. We need the `local_*()` calls in `render_exercise()` to protect against user code changing options, but we're also evaluating checking code that might mess with the options on evaluation. It's _possible_ that authors might want to use options or env vars to communicate between exercises but I doubt it outweighs the benefits of ensuring that exercise evaluation is isolated as much as possible.

2021-06-23 15:36 UTC, gadenbuie requested changes
One more little update (see https://github.com/rstudio/learnr/pull/542#discussion_r657079347) and then we'll be good to go. Can you also please add a NEWS item for this PR? Thank you!

2021-06-23 18:53 UTC, gadenbuie commented
@rossellhayes I added two tests that also check that the checking code doesn't end up modifying the options or env vars. Do you think we've covered all of our bases in the tests?

2021-06-23 18:55 UTC, rossellhayes commented
Good thinking! That all seems good to me, I can't think of anything that's missing

2021-06-23 20:28 UTC, merged