Move error checking from `render_exercise()` to `evaluate_exercise()`
rstudio/learnr pull request #544
Opened 2021-06-22 20:01 UTC by rossellhayes

This is the first step in the process of moving error handling code out of `render_exercise()` and into `evaluate_exercise()`

2021-06-23 15:54 UTC, gadenbuie requested changes
This is a great start and I really like that we'll collect all of the checking logic in one place in `evaluate_exercise()` rather than `render_exercise()`.

The tests are currently written around the error checking logic being inside `render_exercise()` but now that we've moved that out we should

- Update the error-checking tests so they call and reference `evaluate_exercise()`
- Add tests the explicitly check that we get the correct expected errors from `render_exercise()`

2021-06-23 15:54 UTC, gadenbuie commented on R/exercise.R
> +      class = "learnr_exercise_result",
Very minor, but this would be a little more specific:

```suggestion
      class = "learnr_render_exercise_error",
```

2021-06-23 15:54 UTC, gadenbuie commented on tests/testthat/test-exercise.R
> +      )
I don't think we need this. The original test was a little bit complicated because I needed access to `envir_prep`, but now that it's being returned by the error we can use `e$envir_prep`.

We can also skip the `during` step of the test, or rename `before_error` to `during`. There really isn't any benefit to testing "during" since `render_exercise()` doesn't manage the temp directory. I included because I could back when we had the error checking logic in `render_exercise()` but now that it isn't there it's just adding complexity.

2021-06-23 15:59 UTC, gadenbuie commented
For next steps, we can move update the temp directory logic so that we stay in the temp directory while evaluating the checker functions as well. So rather than `with_dir()` we would use `setwd()` and `on.exit()` to coordinate that step. You might also want to move the code checking logic up a bit; there's no need to do anything with the exercise temp directory until after we've performed the code checking.

2021-06-24 03:51 UTC, rossellhayes commented on tests/testthat/test-exercise.R
> +      )
Thanks for this clarification! It was definitely a little hard to understand what was going on in this test when I first edited it

2021-06-24 15:40 UTC, gadenbuie commented on R/exercise.R
> +  on.exit(unlink(exercise_dir), add = TRUE)
I've since realized we can do the same thing with

```suggestion
  withr::local_dir(withr::local_tempdir(pattern = "lrn-ex"))
```

but because we'll need to use `exercise_dir` at some later point (actually in #539) we can do it in two lines

```suggestion
  exercise_dir <- withr::local_tempdir(pattern = "lrn-ex")
  withr::local_dir(exercise_dir)
```

2021-07-09 20:53 UTC, gadenbuie approved these changes
Great work, thank you!

2021-07-09 20:54 UTC, merged