Add handler for underscores to `render_exercise()`
rstudio/learnr pull request #547
Opened 2021-06-25 21:01 UTC by rossellhayes

Adds an error handler in `render_exercise()` for the error caused by running an exercise containing `___`.

This replaces the existing cryptic error – `unexpected input 1: _ ^` – with more user-friendly text – `The exercise contains underscores. Please replace the _ with valid R code.`

2021-06-28 16:21 UTC, gadenbuie requested changes
This looks great, thank you!

One design question: In `gradethis` we give users an (undocumented) option as a way to turn this off or modify how unparseable code is handled. Should we also do that in learnr? Perhaps an option analogous to `exercise.error.check.code`, e.g. `exercise.error.parse.check`. (There may already be a better option in use in learnr.)

2021-06-28 16:21 UTC, gadenbuie commented on tests/testthat/test-exercise.R
> +  expect_match(result$error_message, "contains 2 blanks")
Maybe we should add a test here to make it clear that the code _has to be_ unparseable for the message about blanks, e.g. `user_code = 'cat("____")'` won't return the message about blanks.

2021-06-28 16:21 UTC, gadenbuie commented on R/exercise.R
> +  if (is_exercise_result(parse_results)) {return(parse_results)}
If we decide to make this behavior default and always-on, we could even do this before evaluating the global setup code.

2021-06-28 16:21 UTC, gadenbuie commented on R/exercise.R
> +  if (is_exercise_result(parse_results)) {return(parse_results)}
```suggestion
  if (is_exercise_result(parse_results)) {
    return(parse_results)
  }
```

2021-06-28 17:21 UTC, gadenbuie commented on tests/testthat/test-exercise.R
> +est_that("evaluate_exercise() returns a message if code is unparsable", {
```suggestion
test_that("evaluate_exercise() returns a message if code is unparsable", {
```

2021-06-29 19:23 UTC, rossellhayes commented
Are you thinking an `exercise.parse.error.check` would be implemented with global `options()` or with chunk options?

2021-07-01 16:38 UTC, gadenbuie commented
1. Always run parse checker on submitted code before *any* evaluation
2. Follow the pattern of the `error-check` exercise checker
    - Use the `exercise.checker` function
    - Use the code from `*-parse-check` chunk as the `check_code` for that function
    - Or fall back to the global option `exercise.parse.check.code`
3. If parse failure, return the parse error message with additional friendly feedback

2021-07-02 19:42 UTC, rossellhayes commented
Running into a few test failures on old releases because the new code uses `isFALSE()`, which wasn't available on R < 3.5.
I could:
1. use `backports`,
2. include `isFALSE()` as an internal function, or
3. refactor.

2021-07-06 20:50 UTC, rossellhayes commented
Here's the current state of the checking:
1. Blank checking can be specified with `exercise.blank.check.code`. If it's `FALSE`, no blank checking is performed. If it's `NULL`, the default `exercise_blank_checker()` is called. Otherwise, it can be a function.
2. The default blank check is an `exercise.checker` that marks the exercise incorrect and tells the user how many blanks are still in their code. It detects both parsable (e.g. in strings) and unparsable blanks.
3. Blanks are specified with a regex in the `exercise.blanks` option. This defaults to `"_{3,}"`.
4. If there are no blanks, move to parse checking.
5. Parse checking can be specified with `exercise.blank.check.code`, using the same process as step 1.
6. The default parse check is an `exercise.checker` that marks the exercise as incorrect and an error if the user code cannot be parsed. It gives the same message as `gradethis` (you may have missed a blank, comma, end parenthesis, etc).
7. If the code parses, then the existing process begins: global setup is run, the exercise directory is created, etc.

2021-07-13 16:53 UTC, gadenbuie commented on R/i18n.R
> +  and <- paste0(" $t(text.", and, ") ")
Very much a nit, but we can use old-school glue here.

```suggestion
  and <- sprintf(" $t(text.%s) ", and)
```

2021-07-13 16:56 UTC, gadenbuie commented on R/exercise.R
> +  if (isTruthy(exercise_blanks)) {
Super nit, but let's prefix this so it's clear we didn't come up with our own version.

```suggestion
  if (shiny::isTruthy(exercise_blanks)) {
```

2021-07-13 20:09 UTC, rossellhayes commented on R/exercise.R
> +                        engine = exercise$engine) {
Good catch, that's now a default argument. My original implementation of parse checking and blank checking called `try_checker()` with a different function, but with the three cases that still use it `exercise.checker` is there to access the different check codes within the exercise itself: `exercise$code_check`, `exercise$error_check` and `exercise$check`.

2021-08-20 22:58 UTC, rossellhayes commented
These changes look good to me!

2021-08-23 20:38 UTC, gadenbuie commented on R/exercise.R
> +      return(NULL)
```suggestion
      return()
```

2021-08-23 21:23 UTC, gadenbuie commented on R/exercise.R
> +  if (is.null(blank_feedback) && nzchar(exercise$check)) {
Return `blank_feedback` with output early instead of blending with post-eval check

2021-08-24 14:13 UTC, gadenbuie approved these changes

2021-08-24 15:09 UTC, merged