Improve `run_tutorial()`
rstudio/learnr pull request #601
Opened 2021-10-15 20:09 UTC by gadenbuie

Brings a few new features to `run_tutorial()`:

- Allow `name` to take a path to local tutorial directory. The `name` must be an existing directory and `package` must be `NULL`. Since `run_tutorial()` manages the tutorial directory and uses the `dir` argument of `rmarkdown::run()`, we pre-emptively thorw an error if there is more than one `.Rmd` in the directory and none are named `index.Rmd`. 

- Add arg `clean` to `run_tutorial()`, cleanly re-render the tutorial when `TRUE`. We follow the same logic used in validating the tutorial directory to identify the tutorial `.Rmd` file, since `rmarkdown::shiny_prerendered_clean()` requires a specific file rather than a directory.

- Launch tutorial in viewer pane by default, if possible. It's not currently possible to open tutorials in the tutorial pane interactively, but by giving `launch.browser` a function, we have a place to modify this in the future.

Fixes #600
Fixes #333

2021-10-15 20:25 UTC, rossellhayes commented on R/run.R
> +    stop.("If `name` is a path to a tutorial, it must be the path to a directory containing a signle tutorial.")
```suggestion
    stop.("If `name` is a path to a tutorial, it must be the path to a directory containing a single tutorial.")
```

2021-10-15 20:35 UTC, schloerke requested changes

2021-10-15 20:35 UTC, schloerke commented on R/run.R
> +) {
Should we isolate the args after `...` to allow for easier parameter expansion in the far future? 

```suggestion
  ...,
  shiny_args = NULL,
  clean = FALSE
) {
  ellipsis::check_dots_unnamed()
```

I don't think many people are using `shiny_args` unnamed, so I believe it is an ok change.

2021-10-15 20:35 UTC, schloerke commented on R/run.R
> +  if (!file.exists(path)) {
In windows, this will return `FALSE` if `path` does not end with a `/`.  Maybe append a `/` to `path` if it does not exist?

`?file.exists`
>  (However,
>     directory names must not include a trailing backslash or slash on
>     Windows.)

2021-10-15 20:35 UTC, schloerke commented on R/run.R
> +  rmds <- list.files(path, pattern = "rmd$", ignore.case = TRUE)
Add a `.` to signify the start of the extension

```suggestion
  rmds <- list.files(path, pattern = "\\.rmd$", ignore.case = TRUE)
```

2021-10-15 20:35 UTC, schloerke commented on R/run.R
> +  checkmate::assert_character(package, any.missing = FALSE, max.len = 1, null.ok = TRUE)
Thank you!

2021-10-15 20:35 UTC, schloerke commented on R/run.R
> +    is_interactive <- interactive() ||
Do we import `rlang`? If so....
```suggestion
    is_interactive <- rlang::is_interactive() ||
```

2021-10-15 20:35 UTC, schloerke commented on R/run.R
> +  rmds <- list.files(path, pattern = "rmd$", ignore.case = TRUE)
```suggestion
  rmds <- list.files(path, pattern = "\\.rmd$", ignore.case = TRUE)
```

2021-10-15 20:35 UTC, schloerke commented on R/run.R
> +    )
```suggestion
      'Could not clean shiny prerendered content. Error found while running `rmarkdown::shiny_prerendered_clean("%s")`:\n%s',
      file.path(path, rmds),
      conditionMessage(err)
    )
```

2021-10-15 20:35 UTC, schloerke commented on tests/testthat/test-run.R
> +  expect_error(validate_tutorial_path_is_dir(tmpdir), "No R Markdown files")
Does this fail on windows? I'd be so confused if it doesn't

2021-10-15 20:37 UTC, gadenbuie commented on R/run.R
> +  if (!file.exists(path)) {
gah, I knew there was some kind of Windows path weirdness that would trip me up in here

2021-10-15 20:45 UTC, gadenbuie commented on R/run.R
> +    is_interactive <- interactive() ||
yeah I let this slide, along with a few other places where I would reach for `rlang` because I was thinking it would be better to do an `rlang` upgrade as a concerted effort rather than piecemeal. In this case though I think you're right that it's worth the benefit.

2021-10-15 20:47 UTC, schloerke commented on R/run.R
> +  if (!file.exists(path)) {
idk if it is time to use `fs`?

2021-10-15 20:47 UTC, schloerke commented on R/run.R
> +    is_interactive <- interactive() ||
It could be left as a TODO for later. (The change is independent of the PR goals)

2021-10-18 16:09 UTC, gadenbuie commented on R/run.R
> +  if (!file.exists(path)) {
thanks I went with `path <- sub("/+$", "", path)` (with the `/+` in case there are, somehow, extra trailing slashes)

2021-10-18 16:48 UTC, gadenbuie commented on R/run.R
> +) {
edit: updated to pick the right function: `check_dots_empty()`

2021-10-18 20:07 UTC, schloerke commented on R/run.R
> +#'   `launch.browser` option for `shiny_args`. You can isntead use the
```suggestion
#'   `launch.browser` option for `shiny_args`. You can instead use the
```

2021-10-18 20:11 UTC, schloerke commented on R/run.R
> +  }
Logic is implemented below 

```suggestion
```

2021-10-18 20:26 UTC, schloerke commented on R/run.R
> +      rlang::abort(msg)
`rlang` has this logic implemented and allows for safe followthrough.

```suggestion
      rlang::check_installed(c("rstudioapi", "httpuv"), "Required to run a tutorial as an RStudio job")
```

2021-10-21 18:33 UTC, gadenbuie reviewed
I'm glad I let this sit for a  little bit. Coming back to look at it again, I think the restriction that `name` be a directory when referring to a local file, rather than a packaged tutorial, feels too arbitrary.

I stuck with the directory approach because we move the tutorial directory to a temporary location if we don't have write access where the tutorial is stored. That logic makes sense when the tutorial is hosted in an R package, which may be stored in a location that's inaccessible to the end user. But it doesn't make sense for a local file.

I'm going to update the PR to accept a specific file. If a file name is provided by the directory isn't writeable, we'll throw an error rather than copy the directory.

2021-11-04 16:42 UTC, chendaniely commented
Just got around to using `learnr` + `gradethis` for a randomization experiment.
If i'm reading this correctly,
It seems this PR will fix the issue I'm having with my local `.Rmd` document (not as a package) and on shinyapps.io where my previous attempts are being cached, and I either need to manually "Start Over" or run things in a private/incognito window.  👍 

Will this let me also put in the yaml header so that it never caches the previous attempts? Something like:

```
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: false
    clean: true # <--- this option?
```

2021-12-28 21:34 UTC, rossellhayes approved these changes
This looks good, I just caught a few typos and one potential small improvement

2021-12-28 21:34 UTC, rossellhayes commented on NEWS.md
> +    - `run_tutorial()` can now run local tutorials in addition to tutorial hosted in a package. To run a local tutorial provide the path to the tutorial or the directory containing the tutorial via t
```suggestion
    - `run_tutorial()` can now run local tutorials in addition to tutorials hosted in a package. To run a local tutorial provide the path to the tutorial or the directory containing the tutorial via the `name` argument without providing the `package` argument.
```

2021-12-28 21:34 UTC, rossellhayes commented on NEWS.md
> +    -   learnr tutorials are now run as background RStudio jobs and open in the viewer pane when `run_tutorial()` is called in RStudio. This default is disabled in non-interactive settings or when  `
```suggestion
    -   learnr tutorials are now run as background RStudio jobs and open in the viewer pane when `run_tutorial()` is called in RStudio. This default is disabled in non-interactive settings or when `as_rstudio_job = FALSE`. You can control where the tutorial is opened with the `shiny.launch.browser` global option.
```

2021-12-28 21:34 UTC, rossellhayes commented on R/run.R
> +#'   containing a learnr tutorials, then `package` should not be provided.
```suggestion
#'   containing a learnr tutorial, then `package` should not be provided.
```

2021-12-28 21:34 UTC, rossellhayes commented on R/run.R
> +#'   `shiny.launch.browser` global option to in your current R session to set
```suggestion
#'   `shiny.launch.browser` global option in your current R session to set
```

2021-12-28 21:34 UTC, rossellhayes commented on R/run.R
> +    (is.null(as_rstudio_job) && can_run_rstudio_job())
```suggestion
    (isTRUE(as_rstudio_job) && can_run_rstudio_job(stop_if_not = TRUE)) ||
    (is.null(as_rstudio_job) && can_run_rstudio_job())
```

Including the argument name makes it a little clearer why the two calls to `can_run_rstudio_job()` differ.

2021-12-29 16:11 UTC, gadenbuie commented on R/run.R
> +    (is.null(as_rstudio_job) && can_run_rstudio_job())
Thanks! I stumbled on that line when returning to this PR so I agree it's a good idea to include that argument name.

2021-12-29 16:12 UTC, gadenbuie commented
/document

2021-12-29 17:13 UTC, merged